# generate client keys
---
- name: Copy openssl client extensions
  copy:
    src: "{{ openssl-client.ext }}"
    dest: "{{ openvpn_key_dir }}"
    owner: root
    group: root
    mode: 0400
  when: openssl_client_ext is defined

- name: Copy openssl client extensions
  copy:
    src: openssl-client.ext
    dest: "{{ openvpn_key_dir }}/openssl-client.ext"
    owner: root
    group: root
    mode: 0400
  when: openssl_client_ext is not defined

- name: copy client key
  copy:
    src: "{{ item.key }}"
    dest: "{{ openvpn_key_dir }}/{{ item.username }}.key"
  with_items: "{{ clients }}"
  when: item.key is defined

- name: generate client key
  command: 'openssl req -nodes -newkey rsa:{{ openvpn_rsa_bits }} -keyout {{ item.username }}.key -out {{ item.username }}.csr -days 3650 -subj "/C={{ cert_country_name[:64] }}/ST={{ cert_state[:64] }}/L={{ cert_locality[:64] }}/O={{ cert_org_name[:64] }}/CN={{ inventory_hostname[:64] }}"'
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item.username }}.key"
  with_items: "{{ clients }}"
  when: item.key is not defined

- name: protect client keys
  file:
    path: "{{ openvpn_key_dir }}/{{ item.username }}.key"
    mode: 0400
  with_items: "{{ clients }}"

- name: copy client cert
  copy:
    src: "{{ item.crt }}"
    dest: "{{ openvpn_key_dir }}/{{ item.username }}.crt"
  with_items: "{{ clients }}"
  when: item.crt is defined

- name: sign client key
  command: openssl x509 -req -in {{ item.username }}.csr -out {{ item.username }}.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -extfile openssl-client.ext
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item.username }}.crt"
  with_items: "{{ clients }}"
  when: item.key is not defined

- name: register server ca key
  slurp:
    src: "{{ openvpn_key_dir }}/ca.crt"
  register: ca_cert

- name: register tls-auth key
  slurp:
    src: "{{ openvpn_key_dir }}/ta.key"
  register: tls_auth

- name: register client certs
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item.username }}.crt"
  with_items: "{{ clients }}"
  register: client_certs

- name: register client keys
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item.username }}.key"
  with_items: "{{ clients }}"
  register: client_keys

- name: generate client config
  template:
    src: "{{ openvpn_client_template }}"
    dest: "{{ openvpn_base_dir }}/{{ item.0.item.username }}@{{ openvpn_server_hostname }}.{{ openvpn_port }}.ovpn"
    owner: root
    group: root
    mode: 0400
  with_together:
    - "{{ client_certs.results }}"
    - "{{ client_keys.results }}"

- name: fetch client config
  fetch:
    src: "{{ openvpn_base_dir }}/{{ item.username }}@{{ openvpn_server_hostname }}.{{ openvpn_port }}.ovpn"
    dest: "{{ openvpn_fetch_config_dir }}/{{ item.username }}@{{ openvpn_server_hostname }}.{{ openvpn_port }}.ovpn"
    flat: yes
  with_items: "{{ clients }}"
