---
- name: Create openvpn config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{ openvpn_config_file }}.conf"
    owner: root
    group: root
  notify:
    - restart openvpn

- name: Install LDAP config
  template:
    src: ldap.conf.j2
    dest: "{{ openvpn_base_dir }}/auth/ldap.conf"
    owner: root
    group: root
  when: openvpn_use_ldap

- name: Copy openvpn logrotate config file
  copy:
    src: openvpn_logrotate.conf
    dest: /etc/logrotate.d/openvpn.conf
    owner: root
    group: root
    mode: 0400
  when: ansible_os_family != 'Solaris'

- name: create client config dir
  file:
    path: "{{ openvpn_base_dir }}/{{ openvpn_client_config_dirname }}"
    owner: nobody
    group: nogroup
    state: directory
    mode: 0755
  when: openvpn_client_config_dirname is defined

- name: deine mutter
  debug:
    msg: "{{ openvpn_service_name }}"

- name: setup openvpn auto-start & start
  service:
    name: "{{ openvpn_service_name }}"
    enabled: yes
    state: started
